# Generated by Django 4.2.26 on 2025-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='general_weather',
            field=models.CharField(blank=True, help_text='General weather description', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_options',
            field=models.JSONField(default=list, help_text='Available travel options: bus, car, bike, plane, etc.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather_area',
            field=models.CharField(blank=True, help_text='City/area name for weather API', max_length=200),
        ),
    ]
