# Generated by Django 4.2.26 on 2025-12-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_destination_general_weather_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('image_gallery', models.JSONField(default=list, help_text='List of additional image URLs')),
                ('price_single', models.DecimalField(decimal_places=2, help_text='Price per night for single person', max_digits=10)),
                ('price_couple', models.DecimalField(decimal_places=2, help_text='Price per night for couple', max_digits=10)),
                ('price_executive', models.DecimalField(decimal_places=2, help_text='Price per night for executive room', max_digits=10)),
                ('price_family', models.DecimalField(decimal_places=2, help_text='Price per night for family room', max_digits=10)),
                ('price_entire_hotel', models.DecimalField(blank=True, decimal_places=2, help_text='Price for entire hotel (optional)', max_digits=10, null=True)),
                ('price_villa', models.DecimalField(blank=True, decimal_places=2, help_text='Price for villa (optional)', max_digits=10, null=True)),
                ('amenities', models.JSONField(default=list, help_text='List of amenities: WiFi, Pool, Spa, Restaurant, etc.')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_rooms', models.IntegerField(default=10)),
                ('check_in_time', models.CharField(default='2:00 PM', max_length=20)),
                ('check_out_time', models.CharField(default='12:00 PM', max_length=20)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='recommendations.destination')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
