# Generated by Django 4.2.27 on 2026-01-12 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0003_hotel'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the old constraint
            sql="ALTER TABLE recommendations_review DROP FOREIGN KEY recommendations_review_user_id_3eda23cd_fk_auth_user_id;",
            reverse_sql="",  # Can't easily reverse this
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
