# Generated by Django 4.2.27 on 2025-12-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('bus', 'Bus')], help_text='Type of vehicle', max_length=20, unique=True)),
                ('rate_per_km', models.DecimalField(decimal_places=2, help_text='Rate per kilometer in currency units', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Travel Rate',
                'verbose_name_plural': 'Travel Rates',
                'ordering': ['vehicle_type'],
            },
        ),
    ]
